name: "Test Suite"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  unittest-list-branches:
    name: "Unittest - List Branches"
    runs-on: ubuntu-latest

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v4

    - id: action
      name: "Run Action"
      uses: ./list-branches
      with:
        repository: ${{ github.repository }}

    - name: "Verify Output"
      env:
        RAE_BRANCHES: ${{ steps.action.outputs.branches }}
      run: |
        jq -ce \
            '.[] | select(.name == "main")' \
            <<< "${RAE_BRANCHES}"
        jq -ce \
            '.[] | select(.name == "ci-test-assertion") | select(.date == "2023-04-25T09:36:13Z")' \
            <<< "${RAE_BRANCHES}"

  unittest-expire-branches:
    name: "Unittest - Expire Branches"
    runs-on: ubuntu-latest

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v4

    - name: "Create Test Data"
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
        RAE_REPOSITORY: ${{ github.repository }}
      run: |
        # We create a test-branch which we then delete in a follow-up. This is
        # racy if the test runs several times in parallel. But it is simple
        # enough and can be adjusted if we end up hitting it.
        # We still set "continue-on-error: true" to gracefully avoid failing
        # if the branch was left by a previous failure.
        gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X "POST" \
            "/repos/${RAE_REPOSITORY}/git/refs" \
            -f "ref=refs/heads/ci-test-expired-0" \
            -f "sha=f7a0c3a108e1c91ec05f7bf163e5c410dfc5a636"

    - id: action
      name: "Run Action"
      uses: ./expire-branches
      with:
        date: "1 day ago"
        repository: ${{ github.repository }}
        wildcard: "ci-test-expired-*"

    - name: "Verify Output"
      env:
        RAE_BRANCHES: ${{ steps.action.outputs.branches }}
      run: |
        [[ "${RAE_BRANCHES}" == '["ci-test-expired-0"]' ]]
