name: "Test Suite"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "wip/**" ]

jobs:
  unittest-list-branches:
    name: "Unittest - List Branches"
    runs-on: ubuntu-latest

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3

    - id: action
      name: "Run Action"
      uses: ./list-branches
      with:
        repository: ${{ github.repository }}

    - name: "Verify Output"
      env:
        RAE_BRANCHES: ${{ steps.action.outputs.branches }}
      run: |
        jq -ce \
            '.[] | select(.name == "main")' \
            <<< "${RAE_BRANCHES}"
        jq -ce \
            '.[] | select(.name == "ci-test-assertion") | select(.date == "2023-04-25T09:36:13Z")' \
            <<< "${RAE_BRANCHES}"
      shell: bash
